version: 2

models:
  - name: test_model_one
    description: "test layout example one"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: test_model_two
    description: "test layout example two"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
